// -----------------------------------------------------------------------------
// Vena Blockly
// Visual scripting block graph runtime for the Vena open-source Unity framework.
// Copyright (c) Nan Li.
// Licensed under the terms defined in the repository LICENSE file.
// -----------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Vena.Blockly.Editor
{

    /// <summary>
    /// 三件套 emitter：把 <see cref="ScannedSource"/> 集合写盘为 `<源类名>.g.cs`。
    /// 每个被扫描源类一个 .g.cs，含其全部 [Blockly] 成员（method / property / field）的三件套（Impl + Source + Source.Node）。
    /// 产物落点：`<源类目录>/Generated/<源类名>.g.cs`（per-source，命名空间 = `<源类命名空间>.Generated`）。
    /// Provider 产物（聚合所有 NodeMetadata）落在 <c>outputRoot</c>，命名空间固定 <c>Vena.Blockly.Generated</c>。
    /// </summary>
    internal static class CodeWriter
    {
        /// <summary>
        /// 显式 CRLF —— emitter 输出行尾 OS-无关、确定性，幂等性的关键。
        /// 不依赖 <see cref="StringBuilder.AppendLine()"/>（其用 <see cref="Environment.NewLine"/>）。
        /// </summary>
        private const string NL = "\r\n";

        /// <summary>
        /// .g.cs 头注释（7 行）。所有产物文件共用，调用点紧随其后追加一个 <see cref="NL"/> 形成强制空行。
        /// </summary>
        private const string AutoGeneratedHeader =
            "// -----------------------------------------------------------------------------\r\n" +
            "// <auto-generated>\r\n" +
            "//   Generated by the com.vena.blockly Blockly codegen pipeline.\r\n" +
            "//   Do not edit manually. Changes will be overwritten on next codegen run.\r\n" +
            "// </auto-generated>\r\n" +
            "// -----------------------------------------------------------------------------\r\n";

        /// <summary>
        /// 默认写盘模式：对每个源类，产出 <c>&lt;src.SourceDirectory&gt;/Generated/&lt;源类名&gt;.g.cs</c>
        /// （命名空间 = `&lt;源类命名空间&gt;.Generated`，与源类物理目录平行）；
        /// Provider 产物落到 <paramref name="outputRoot"/>（命名空间 <c>Vena.Blockly.Generated</c>）。
        /// 文件头打 auto-generated 标记。返回每次实际写盘 / 跳过（内容相同）的统计。
        /// </summary>
        public static EmitReport Emit(IReadOnlyList<ScannedSource> sources, string outputRoot)
        {
            if (sources == null) throw new ArgumentNullException(nameof(sources));
            if (string.IsNullOrEmpty(outputRoot)) throw new ArgumentException("outputRoot 不能为空", nameof(outputRoot));

            var report = new EmitReport();

            foreach (var src in sources)
            {
                if (string.IsNullOrEmpty(src.SourceDirectory))
                {
                    throw new InvalidOperationException(
                        $"[Vena.Blockly] 无法定位源类物理目录: {src.SourceType.FullName}");
                }
                var perSourceDir = Path.Combine(src.SourceDirectory, "Generated");
                Directory.CreateDirectory(perSourceDir);

                var content = EmitSourceFile(src);
                var path = Path.Combine(perSourceDir, src.SourceType.Name + ".g.cs").Replace('\\', '/');
                WriteIfChanged(path, content, report);
            }

            // Provider 产物：聚合所有 *Source 的 NodeMetadata，运行期由 IBlocklyNodeFactory.Initialize() 加载。
            Directory.CreateDirectory(outputRoot);
            var providerContent = EmitProviderFile(sources);
            var providerPath = Path.Combine(outputRoot, "GeneratedNodeMetadataProvider.g.cs").Replace('\\', '/');
            WriteIfChanged(providerPath, providerContent, report);

            return report;
        }

        /// <summary>
        /// Sample 覆盖模式：把 <paramref name="targetFile"/> 内 `#region Impl` / `#region Source` 区段
        /// 替换为 <paramref name="src"/> 的生成产物（保留区段外的源类等手写部分）。区段不存在则报错。
        /// </summary>
        public static EmitReport EmitInplaceRegions(ScannedSource src, string targetFile)
        {
            if (src == null) throw new ArgumentNullException(nameof(src));
            if (string.IsNullOrEmpty(targetFile)) throw new ArgumentException("targetFile 不能为空", nameof(targetFile));
            if (!File.Exists(targetFile)) throw new FileNotFoundException("Sample 文件不存在", targetFile);

            var report = new EmitReport();
            var original = File.ReadAllText(targetFile);

            var implBlock = BuildImplsBlock(src);
            var sourceBlock = BuildSourcesBlock(src);

            var replaced = ReplaceRegion(original, "Impl", implBlock);
            replaced = ReplaceRegion(replaced, "Source", sourceBlock);

            WriteIfChanged(targetFile, replaced, report);
            return report;
        }

        /// <summary>
        /// 生成完整 .g.cs 文件内容（独立编译单元）：auto-generated 头 + using + namespace + 所有成员的三件套。
        /// 命名空间 = `&lt;源类命名空间&gt;.Generated`（源类无命名空间时退化为 `Generated`），始终有 namespace 块。
        /// </summary>
        private static string EmitSourceFile(ScannedSource src)
        {
            var sb = new StringBuilder(4096);
            sb.Append(AutoGeneratedHeader).Append(NL);
            sb.Append("using Vena.Blockly;").Append(NL);
            sb.Append(NL);

            var srcNs = src.SourceType.Namespace;
            var ns = string.IsNullOrEmpty(srcNs) ? "Generated" : srcNs + ".Generated";

            sb.Append("namespace ").Append(ns).Append(NL);
            sb.Append("{").Append(NL);
            sb.Append(NL);

            AppendImpls(sb, src, hasNs: true);
            sb.Append(NL);
            AppendSources(sb, src, hasNs: true);

            sb.Append("}").Append(NL);

            return sb.ToString();
        }

        /// <summary>
        /// 聚合 provider 文件：所有源类下的 NodeMetadata 注册为 <see cref="INodeMetadataProvider"/>。
        /// 运行期由 <c>IBlocklyNodeFactory.Initialize()</c> 实例化 + 装载。
        /// </summary>
        private static string EmitProviderFile(IReadOnlyList<ScannedSource> sources)
        {
            var sb = new StringBuilder(4096);
            sb.Append(AutoGeneratedHeader).Append(NL);
            sb.Append("using System;").Append(NL);
            sb.Append("using System.Collections.Generic;").Append(NL);
            sb.Append("using Vena.Blockly;").Append(NL);
            sb.Append(NL);

            sb.Append("namespace Vena.Blockly.Generated").Append(NL);
            sb.Append("{").Append(NL);
            sb.Append(NL);
            sb.Append("    public sealed class GeneratedNodeMetadataProvider : INodeMetadataProvider").Append(NL);
            sb.Append("    {").Append(NL);
            sb.Append("        private readonly Dictionary<Type, NodeMetadata> _byType;").Append(NL);
            sb.Append("        private readonly NodeMetadata[] _all;").Append(NL);
            sb.Append(NL);
            sb.Append("        public GeneratedNodeMetadataProvider()").Append(NL);
            sb.Append("        {").Append(NL);
            sb.Append("            _all = new NodeMetadata[]").Append(NL);
            sb.Append("            {").Append(NL);

            foreach (var src in sources)
            {
                foreach (var m in src.Members)
                {
                    AppendNodeMetadataCtor(sb, src, m, "                ");
                }
            }

            sb.Append("            };").Append(NL);
            sb.Append("            _byType = new Dictionary<Type, NodeMetadata>(_all.Length);").Append(NL);
            sb.Append("            for (int i = 0; i < _all.Length; i++) { _byType[_all[i].SourceType] = _all[i]; }").Append(NL);
            sb.Append("        }").Append(NL);
            sb.Append(NL);
            sb.Append("        public bool TryGet(Type sourceType, out NodeMetadata metadata)").Append(NL);
            sb.Append("        {").Append(NL);
            sb.Append("            return _byType.TryGetValue(sourceType, out metadata);").Append(NL);
            sb.Append("        }").Append(NL);
            sb.Append(NL);
            sb.Append("        public IReadOnlyList<NodeMetadata> All() => _all;").Append(NL);
            sb.Append("    }").Append(NL);
            sb.Append("}").Append(NL);
            return sb.ToString();
        }

        private static void AppendNodeMetadataCtor(StringBuilder sb, ScannedSource src, ScannedMember m, string indent)
        {
            var srcName = SourceName(src.SourceType, m);
            var ns = src.SourceType.Namespace;
            var generatedNs = string.IsNullOrEmpty(ns) ? "Generated" : ns + ".Generated";
            var srcFqn = generatedNs + "." + srcName;
            var slots = BuildSlotList(m);

            sb.Append(indent).Append("new NodeMetadata(").Append(NL);
            sb.Append(indent).Append("    sourceType: typeof(").Append(srcFqn).Append("),").Append(NL);
            sb.Append(indent).Append("    nodeType: typeof(").Append(srcFqn).Append(".Node),").Append(NL);
            sb.Append(indent).Append("    menuPath: \"").Append(EscapeStringLiteral(m.MenuPath)).Append("\",").Append(NL);
            sb.Append(indent).Append("    properties: new NodePropertyMetadata[]").Append(NL);
            sb.Append(indent).Append("    {").Append(NL);
            foreach (var slot in slots)
            {
                sb.Append(indent).Append("        new NodePropertyMetadata(\"")
                    .Append(EscapeStringLiteral(slot.DisplayName)).Append("\", ")
                    .Append(slot.Order).Append(", \"")
                    .Append(slot.FieldName).Append("\", typeof(")
                    .Append(TypeRef(slot.PopType)).Append(")),").Append(NL);
            }
            sb.Append(indent).Append("    }),").Append(NL);
        }

        /// <summary>仅生成 Impl 区块体（不含 namespace 头）—— sample 覆盖模式专用。</summary>
        private static string BuildImplsBlock(ScannedSource src)
        {
            var sb = new StringBuilder(2048);
            sb.Append("    #region Impl").Append(NL);
            sb.Append(NL);
            AppendImpls(sb, src, hasNs: true);
            sb.Append("    #endregion");
            return sb.ToString();
        }

        /// <summary>仅生成 Source 区块体（不含 namespace 头）—— sample 覆盖模式专用。</summary>
        private static string BuildSourcesBlock(ScannedSource src)
        {
            var sb = new StringBuilder(2048);
            sb.Append("    #region Source").Append(NL);
            sb.Append(NL);
            AppendSources(sb, src, hasNs: true);
            sb.Append("    #endregion");
            return sb.ToString();
        }

        // ---- Impl 三件套之一：纯逻辑容器 ----

        private static void AppendImpls(StringBuilder sb, ScannedSource src, bool hasNs)
        {
            var indent = hasNs ? "    " : "";
            for (int i = 0; i < src.Members.Count; i++)
            {
                if (i > 0) sb.Append(NL);
                AppendImpl(sb, src.SourceType, src.Members[i], indent);
            }
        }

        private static void AppendImpl(StringBuilder sb, Type sourceType, ScannedMember m, string indent)
        {
            var implName = ImplName(sourceType, m);
            var isProcedure = m.ReturnType == typeof(void);
            var implIface = isProcedure ? "IProcedureImpl" : $"IFunctionImpl<{TypeRef(m.ReturnType)}>";
            var srcRef = TypeRef(sourceType);

            sb.Append(indent).Append("public sealed class ").Append(implName).Append(" : ").Append(implIface).Append(NL);
            sb.Append(indent).Append("{").Append(NL);

            var emittedField = false;

            if (RequiresInstanceField(m))
            {
                sb.Append(indent).Append("    public ").Append(srcRef).Append(" instance;").Append(NL);
                emittedField = true;
            }

            foreach (var p in m.Parameters)
            {
                if (emittedField) sb.Append(NL);
                sb.Append(indent).Append("    public ").Append(TypeRef(p.ParameterType)).Append(' ').Append(p.Identifier).Append(";").Append(NL);
                emittedField = true;
            }

            if (emittedField) sb.Append(NL);
            if (isProcedure)
            {
                sb.Append(indent).Append("    public void Evaluate()").Append(NL);
            }
            else
            {
                sb.Append(indent).Append("    public ").Append(TypeRef(m.ReturnType)).Append(" Evaluate()").Append(NL);
            }
            sb.Append(indent).Append("    {").Append(NL);
            sb.Append(indent).Append("        ").Append(EvaluateCallSite(sourceType, m)).Append(NL);
            sb.Append(indent).Append("    }").Append(NL);

            sb.Append(indent).Append("}").Append(NL);
        }

        private static string EvaluateCallSite(Type sourceType, ScannedMember m)
        {
            var receiver = m.IsStatic ? TypeRef(sourceType) : "instance";
            var args = string.Join(", ", m.Parameters.Select(p => p.Identifier));
            switch (m.Kind)
            {
                case ScannedMemberKind.Method:
                    {
                        var call = $"{receiver}.{m.MemberName}({args})";
                        return m.ReturnType == typeof(void) ? call + ";" : "return " + call + ";";
                    }
                case ScannedMemberKind.PropertyGetter:
                    return $"return {receiver}.{m.MemberName};";
                case ScannedMemberKind.PropertySetter:
                    {
                        var valueIdent = m.Parameters[0].Identifier;
                        return $"{receiver}.{m.MemberName} = {valueIdent};";
                    }
                default:
                    throw new InvalidOperationException($"Unknown member kind: {m.Kind}");
            }
        }

        // ---- Source + Source.Node 三件套之二/三 ----

        private static void AppendSources(StringBuilder sb, ScannedSource src, bool hasNs)
        {
            var indent = hasNs ? "    " : "";
            for (int i = 0; i < src.Members.Count; i++)
            {
                if (i > 0) sb.Append(NL);
                AppendSource(sb, src.SourceType, src.Members[i], indent);
            }
        }

        private static void AppendSource(StringBuilder sb, Type sourceType, ScannedMember m, string indent)
        {
            var implName = ImplName(sourceType, m);
            var srcName = SourceName(sourceType, m);
            var isProcedure = m.ReturnType == typeof(void);
            var baseType = isProcedure
                ? $"Procedure<{implName}>"
                : $"Function<{implName}, {TypeRef(m.ReturnType)}>";

            var slots = BuildSlotList(m);

            sb.Append(indent).Append("[BlocklySource(\"").Append(EscapeStringLiteral(m.MenuPath))
                .Append("\", typeof(").Append(srcName).Append(".Node))]").Append(NL);
            sb.Append(indent).Append("public sealed class ").Append(srcName).Append(" : ").Append(baseType).Append(NL);
            sb.Append(indent).Append("{").Append(NL);

            foreach (var slot in slots)
            {
                sb.Append(indent).Append("    [BlocklySourceProperty(\"").Append(EscapeStringLiteral(slot.DisplayName))
                    .Append("\", ").Append(slot.Order).Append(")]").Append(NL);
                sb.Append(indent).Append("    public ").Append(slot.SlotType).Append(' ').Append(slot.FieldName).Append(";").Append(NL);
                sb.Append(NL);
            }

            AppendNode(sb, srcName, implName, slots, indent + "    ");
            sb.Append(indent).Append("}").Append(NL);
        }

        private static void AppendNode(StringBuilder sb, string srcName, string implName, IReadOnlyList<SlotInfo> slots, string indent)
        {
            sb.Append(indent).Append("sealed class Node : Block<").Append(srcName).Append(">").Append(NL);
            sb.Append(indent).Append("{").Append(NL);

            foreach (var slot in slots)
            {
                sb.Append(indent).Append("    private ILogicNode _").Append(slot.FieldName).Append(";").Append(NL);
            }
            sb.Append(NL);

            sb.Append(indent).Append("    protected override void Initialize()").Append(NL);
            sb.Append(indent).Append("    {").Append(NL);
            foreach (var slot in slots)
            {
                sb.Append(indent).Append("        _").Append(slot.FieldName)
                    .Append(" = Blockly.CreateBlock(source.").Append(slot.FieldName).Append(");").Append(NL);
            }
            sb.Append(indent).Append("    }").Append(NL);
            sb.Append(NL);

            // EvaluateChildren：按 order 升序触发子节点 Evaluate（每个子 Push 一次值到栈）。
            // 5 步协议（合约 §4 / Editor §2）锁定：所有子节点 Push 必须先于 Pop，因此 Evaluate 不能再混在
            // InitializeProperties 里——否则栈是空的，Pop 立刻撞底。
            sb.Append(indent).Append("    protected override void EvaluateChildren()").Append(NL);
            sb.Append(indent).Append("    {").Append(NL);
            foreach (var slot in slots)
            {
                sb.Append(indent).Append("        _").Append(slot.FieldName).Append(".Evaluate();").Append(NL);
            }
            sb.Append(indent).Append("    }").Append(NL);
            sb.Append(NL);

            // InitializeProperties：仅 Pop + 字段拷贝，无副作用。栈是 LIFO——Push 顺序 = order 升序，
            // 因此 Pop 顺序 = order 降序（最后入栈的最先出栈）。
            sb.Append(indent).Append("    protected override void InitializeProperties(")
                .Append(implName).Append(" impl)").Append(NL);
            sb.Append(indent).Append("    {").Append(NL);
            for (int i = slots.Count - 1; i >= 0; i--)
            {
                var slot = slots[i];
                sb.Append(indent).Append("        impl.").Append(slot.FieldName)
                    .Append(" = Blockly.Pop<").Append(TypeRef(slot.PopType)).Append(">();").Append(NL);
            }
            sb.Append(indent).Append("    }").Append(NL);
            sb.Append(NL);

            sb.Append(indent).Append("    protected override void CleanProperties(")
                .Append(implName).Append(" impl)").Append(NL);
            sb.Append(indent).Append("    {").Append(NL);
            foreach (var slot in slots)
            {
                if (!slot.PopTypeIsReference) continue;
                sb.Append(indent).Append("        impl.").Append(slot.FieldName).Append(" = null;").Append(NL);
            }
            sb.Append(indent).Append("    }").Append(NL);
            sb.Append(NL);

            sb.Append(indent).Append("    protected override void OnDestroy()").Append(NL);
            sb.Append(indent).Append("    {").Append(NL);
            foreach (var slot in slots)
            {
                sb.Append(indent).Append("        Blockly.DestroyBlock(_").Append(slot.FieldName).Append(");").Append(NL);
                sb.Append(indent).Append("        _").Append(slot.FieldName).Append(" = null;").Append(NL);
            }
            sb.Append(indent).Append("    }").Append(NL);

            sb.Append(indent).Append("}").Append(NL);
        }

        // ---- 命名规则 ----

        /// <summary>
        /// 命名规则：`*Impl` = `<源类简名><成员名>Impl`，源类简名取 <c>sourceType.Name</c>。
        /// 字面拼接更通用、可泛化、无歧义。冲突由 <see cref="SourceName"/> 追加 `Source` 后缀解决。
        /// </summary>
        private static string ImplName(Type sourceType, ScannedMember m) => sourceType.Name + MemberSuffix(m) + "Impl";

        /// <summary>命名规则：`*Source` = `<源类简名><成员名>`；与源类同名时追加 `Source` 后缀消歧。</summary>
        private static string SourceName(Type sourceType, ScannedMember m)
        {
            var candidate = sourceType.Name + MemberSuffix(m);
            return candidate == sourceType.Name ? candidate + "Source" : candidate;
        }

        private static string MemberSuffix(ScannedMember m)
        {
            switch (m.Kind)
            {
                case ScannedMemberKind.Method: return m.MemberName;
                case ScannedMemberKind.PropertyGetter: return m.MemberName + "Getter";
                case ScannedMemberKind.PropertySetter: return m.MemberName + "Setter";
                default: throw new InvalidOperationException($"Unknown member kind: {m.Kind}");
            }
        }

        // ---- 槽位构建（顺序锁：UI ≡ IR ≡ Pop） ----

        private static bool RequiresInstanceField(ScannedMember m) => !m.IsStatic;

        private static IReadOnlyList<SlotInfo> BuildSlotList(ScannedMember m)
        {
            // 按 order 升序固定 UI / IR / Pop 三者一致顺序：
            // 1) instance（若需）
            // 2) 参数（method 走 [Blockly].parameterNames 顺序；property / field setter 走单 value 槽）
            var list = new List<SlotInfo>();
            int order = 1;

            if (RequiresInstanceField(m))
            {
                list.Add(new SlotInfo(
                    fieldName: "instance",
                    displayName: "实例",
                    order: order++,
                    slotType: "Expression",
                    popType: m.DeclaringType,
                    popTypeIsReference: !m.DeclaringType.IsValueType));
            }

            foreach (var p in m.Parameters)
            {
                list.Add(new SlotInfo(
                    fieldName: p.Identifier,
                    displayName: p.DisplayName,
                    order: order++,
                    slotType: "Expression",
                    popType: p.ParameterType,
                    popTypeIsReference: !p.ParameterType.IsValueType));
            }

            return list;
        }

        private sealed class SlotInfo
        {
            public string FieldName { get; }
            public string DisplayName { get; }
            public int Order { get; }
            public string SlotType { get; }
            public Type PopType { get; }
            public bool PopTypeIsReference { get; }

            public SlotInfo(string fieldName, string displayName, int order, string slotType, Type popType, bool popTypeIsReference)
            {
                FieldName = fieldName;
                DisplayName = displayName;
                Order = order;
                SlotType = slotType;
                PopType = popType;
                PopTypeIsReference = popTypeIsReference;
            }
        }

        // ---- 类型/字面量打印 ----

        /// <summary>
        /// C# 类型引用打印。处理：void / 内置基元别名 / 泛型 / 嵌套类。不处理：array、ref/in/out、tuple。
        /// 当前 codegen 输入面（[Blockly] method / property / field 参数）只有非 ref 普通类型，足够。
        /// </summary>
        private static string TypeRef(Type t)
        {
            if (t == typeof(void)) return "void";
            if (t == typeof(bool)) return "bool";
            if (t == typeof(byte)) return "byte";
            if (t == typeof(sbyte)) return "sbyte";
            if (t == typeof(short)) return "short";
            if (t == typeof(ushort)) return "ushort";
            if (t == typeof(int)) return "int";
            if (t == typeof(uint)) return "uint";
            if (t == typeof(long)) return "long";
            if (t == typeof(ulong)) return "ulong";
            if (t == typeof(float)) return "float";
            if (t == typeof(double)) return "double";
            if (t == typeof(decimal)) return "decimal";
            if (t == typeof(string)) return "string";
            if (t == typeof(object)) return "object";

            if (t.IsGenericType)
            {
                var def = t.GetGenericTypeDefinition();
                var name = def.Name;
                var tickIdx = name.IndexOf('`');
                if (tickIdx >= 0) name = name.Substring(0, tickIdx);
                var ns = string.IsNullOrEmpty(def.Namespace) ? "" : def.Namespace + ".";
                var args = string.Join(", ", t.GetGenericArguments().Select(TypeRef));
                return ns + name + "<" + args + ">";
            }

            if (t.IsNested && t.DeclaringType != null)
            {
                return TypeRef(t.DeclaringType) + "." + t.Name;
            }

            return string.IsNullOrEmpty(t.Namespace) ? t.Name : (t.Namespace + "." + t.Name);
        }

        private static string EscapeStringLiteral(string s)
        {
            if (string.IsNullOrEmpty(s)) return string.Empty;
            return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }

        // ---- 文件 IO ----

        /// <summary>
        /// 幂等写盘：若目标文件存在且内容字节级一致，则跳过；否则覆写。统计计入 <paramref name="report"/>。
        /// </summary>
        private static void WriteIfChanged(string path, string content, EmitReport report)
        {
            if (File.Exists(path))
            {
                var existing = File.ReadAllText(path);
                if (string.Equals(existing, content, StringComparison.Ordinal))
                {
                    report.Unchanged.Add(path);
                    return;
                }
            }
            File.WriteAllText(path, content);
            report.Written.Add(path);
        }

        // ---- region 替换 ----

        /// <summary>
        /// 在 <paramref name="original"/> 中找到 `#region <regionName>` ... `#endregion` 段（支持嵌套），
        /// 用 <paramref name="newBlock"/> 整体替换（保留 region 自身行）。`newBlock` 应已含 `#region ... #endregion` 头尾。
        /// 输出统一用 CRLF，与 emitter 内部一致。
        /// </summary>
        private static string ReplaceRegion(string original, string regionName, string newBlock)
        {
            var lines = original.Split(new[] { "\r\n", "\n" }, StringSplitOptions.None);

            int startLine = -1, endLine = -1;
            int depth = 0;
            for (int i = 0; i < lines.Length; i++)
            {
                var trimmed = lines[i].TrimStart();
                if (startLine < 0)
                {
                    if (trimmed.StartsWith("#region", StringComparison.Ordinal))
                    {
                        var rest = trimmed.Substring("#region".Length).Trim();
                        if (rest == regionName)
                        {
                            startLine = i;
                            depth = 1;
                            continue;
                        }
                    }
                }
                else
                {
                    if (trimmed.StartsWith("#region", StringComparison.Ordinal)) depth++;
                    else if (trimmed.StartsWith("#endregion", StringComparison.Ordinal))
                    {
                        depth--;
                        if (depth == 0)
                        {
                            endLine = i;
                            break;
                        }
                    }
                }
            }

            if (startLine < 0 || endLine < 0)
            {
                throw new InvalidOperationException($"#region {regionName} 未在目标文件中找到。");
            }

            var sb = new StringBuilder(original.Length);
            for (int i = 0; i < startLine; i++)
            {
                sb.Append(lines[i]).Append(NL);
            }
            sb.Append(newBlock).Append(NL);
            for (int i = endLine + 1; i < lines.Length; i++)
            {
                sb.Append(lines[i]);
                if (i < lines.Length - 1) sb.Append(NL);
            }
            return sb.ToString();
        }
    }

    /// <summary>emit 写盘统计：写入路径 / 跳过路径分别计数。</summary>
    internal sealed class EmitReport
    {
        public List<string> Written { get; } = new List<string>();
        public List<string> Unchanged { get; } = new List<string>();

        public override string ToString()
            => $"written={Written.Count}, unchanged={Unchanged.Count}";
    }
}
